packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
allowBuilds:
  '@huanlin/dsh-plugin-mineru@git+https://github.com/HuanLinOTO/dsh-plugin-mineru.git#edfab2bf0b7a1083beeaef90947d1096a31ca84b': true
  cloudflared: true
  cpu-features: true
  node-pty: true
  sharp: true
  ssh2: true
  tesseract.js: true
minimumReleaseAgeExclude:
  - dshmarket@1.3.0 || 1.9.0
  - '@linxin666/dsh-client-ui-aionui-panel@0.1.17 || 0.2.7'
  - '@linxin666/dsh-client-ui-git-graph@0.1.17 || 0.2.7'
  - '@linxin666/dsh-client-ui-skin-center@0.1.17 || 0.2.7'
  - '@linxin666/dsh-client-ui-task-board@0.1.17 || 0.2.7'
  - '@linxin666/dsh-client-ui-web-ui-settings@0.1.17 || 0.2.7'
  - '@linxin666/dsh-liangshen@0.1.17 || 0.2.7'
  - '@linxin666/dsh-live-stats@0.1.17'
  - '@linxin666/dsh-pet@0.1.17 || 0.2.7'
  - '@linxin666/dsh-remote-web-ui@0.1.17 || 0.2.7'
  - '@linxin666/dsh-skins@0.1.17 || 0.2.7'
  - '@linxin666/dsh-ssh@0.1.17 || 0.2.7'
  - '@linxin666/dsh-tool-describe-image@0.1.17 || 0.2.7'
  - '@linxin666/dsh-web-ui-all@0.1.17 || 0.2.7'
  - dsh-file-upload@0.4.2
  - '@linxin666/dsh-chat-recovery@0.2.7'
  - '@linxin666/dsh-client-ui-community-plugins@0.2.7'
  - '@linxin666/dsh-client-ui-plugin-manager@0.2.7'
  - '@linxin666/dsh-client-ui-skill-explorer@0.2.7'
  - '@linxin666/dsh-desktop-launcher@0.2.7'
